$axure.loadCurrentPage({
  "url":"step2_3.html",
  "generationDate":new Date(1421638851167.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c7a09f39caf64edb99b400cd811db2e7",
    "type":"Axure:Page",
    "name":"step2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52efc823b20c448ca6754faeafd24365",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcebe6b1fb924382829cc10e810a10ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/step2_2/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "52efc823b20c448ca6754faeafd24365":{
      "scriptId":"u0"},
    "dcebe6b1fb924382829cc10e810a10ec":{
      "scriptId":"u1"}}});