$axure.loadCurrentPage({
  "url":"未注册_1.html",
  "generationDate":new Date(1421638851106.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a9d7dc3738fe4abb9f9c88a3a10276d1",
    "type":"Axure:Page",
    "name":"未注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3bb559290a7c47a5903307bb1c5f6a86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d5f5df5a6c54951af8ef27e73b62b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未注册/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3bb559290a7c47a5903307bb1c5f6a86":{
      "scriptId":"u0"},
    "7d5f5df5a6c54951af8ef27e73b62b93":{
      "scriptId":"u1"}}});