$axure.loadCurrentPage({
  "url":"选择公历生日.html",
  "generationDate":new Date(1421638850819.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8225ede7bcee4c2c819af564b3164fbb",
    "type":"Axure:Page",
    "name":"选择公历生日",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"275980fb67f8473bae64deb06c272c23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":693}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f8369be4e5b44c1881bccb8d333d1d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":693}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"此处为选择出生日期界面"},
          "images":{
            "normal~":"images/选择公历生日/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "275980fb67f8473bae64deb06c272c23":{
      "scriptId":"u0"},
    "1f8369be4e5b44c1881bccb8d333d1d6":{
      "scriptId":"u1"}}});