$axure.loadCurrentPage({
  "url":"微博.html",
  "generationDate":new Date(1421638850915.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"616d02a451d842d1929280e5fc90002a",
    "type":"Axure:Page",
    "name":"微博",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"80bfd57edd9f458fbd2d45239dbd4638",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":70},
            "size":{
              "width":30,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fe95681e6504070a36c63065944f483",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":70},
                "size":{
                  "width":30,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微博/u0.png"}},
{
          "id":"47c140cb30f74c76baa0bdc3c388d90a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":160,
              "y":60},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c226e3a12646999a74be22b2f12aee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":160,
                  "y":60},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ee1a3f0c24f454f932e5938a0db8833",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 常规', '宋体'",
            "fontSize":"12px",
            "location":{
              "x":162,
              "y":78},
            "size":{
              "width":97,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eaaaadf915c4e0398f689a92b3ea297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 常规', '宋体'",
                "fontSize":"12px",
                "location":{
                  "x":162,
                  "y":78},
                "size":{
                  "width":97,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a92db94183d4ba48aaf2a6602cdd5a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":162,
              "y":102},
            "size":{
              "width":200,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2cf75a4260143d6984747096b769ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":162,
                  "y":102},
                "size":{
                  "width":200,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微博/u6.png"}},
{
          "id":"e414d3b7180a42429a22555d664f34b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":205,
              "y":113},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b976cfcdafcb47bb833a0c03dafe6c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":113},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "80bfd57edd9f458fbd2d45239dbd4638":{
      "scriptId":"u0"},
    "0fe95681e6504070a36c63065944f483":{
      "scriptId":"u1"},
    "47c140cb30f74c76baa0bdc3c388d90a":{
      "scriptId":"u2"},
    "79c226e3a12646999a74be22b2f12aee":{
      "scriptId":"u3"},
    "5ee1a3f0c24f454f932e5938a0db8833":{
      "scriptId":"u4"},
    "3eaaaadf915c4e0398f689a92b3ea297":{
      "scriptId":"u5"},
    "4a92db94183d4ba48aaf2a6602cdd5a9":{
      "scriptId":"u6"},
    "f2cf75a4260143d6984747096b769ef4":{
      "scriptId":"u7"},
    "e414d3b7180a42429a22555d664f34b1":{
      "scriptId":"u8"},
    "b976cfcdafcb47bb833a0c03dafe6c96":{
      "scriptId":"u9"}}});