$axure.loadCurrentPage({
  "url":"step1_2.html",
  "generationDate":new Date(1421638851160.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1ea9419fec3144579d00d09b648c7b92",
    "type":"Axure:Page",
    "name":"step1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4e71ee8e36a5417a93a3d0fb696a760a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":693}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ea2163bfdd94acd82213da4c0c59639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":693}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"已登录用户：自动识别用户姓名，可更改，同时同步到站内。选择性别。<br>判断用户在天际网是否有好友，没有的话只显示“查看通讯录联系人”。有好友的话则两个按钮都显示。点击某个就计算出对应的结果。"},
          "images":{
            "normal~":"images/step1_2/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4e71ee8e36a5417a93a3d0fb696a760a":{
      "scriptId":"u0"},
    "5ea2163bfdd94acd82213da4c0c59639":{
      "scriptId":"u1"}}});