$axure.loadCurrentPage({
  "url":"step3_4.html",
  "generationDate":new Date(1421638851332.83),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"48b3a07eb4a84412989c0b82a79ae2df",
    "type":"Axure:Page",
    "name":"step3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"94f759c83f394290a19148528fdf3560",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":1300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b273b710ddc04553824a26537a4ea8d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":1300}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"已登录：<br>显示求签文字，点击“告诉小伙伴”显示分享页面。根据用户选择的薪水范围、地区、行业、职能推出相对应的公司。"},
          "images":{
            "normal~":"images/step3_4/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "94f759c83f394290a19148528fdf3560":{
      "scriptId":"u0"},
    "b273b710ddc04553824a26537a4ea8d4":{
      "scriptId":"u1"}}});