$axure.loadCurrentPage({
  "url":"step1_4.html",
  "generationDate":new Date(1421638851311.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d470d7d4a546482e96e5d00d7d37f68e",
    "type":"Axure:Page",
    "name":"step1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ac2c728228634d1a870891c6e81d17b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":693}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"647a8376bc6c4cd5b904796361e1625e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":693}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"已登录用户：<br>选择期望薪水、自动识别用户已填写的地区、行业、职能。用户可更改当前行业以及职能和地区。但不会同步到网站。"},
          "images":{
            "normal~":"images/step1_4/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ac2c728228634d1a870891c6e81d17b1":{
      "scriptId":"u0"},
    "647a8376bc6c4cd5b904796361e1625e":{
      "scriptId":"u1"}}});