$axure.loadCurrentPage({
  "url":"step2_2.html",
  "generationDate":new Date(1421638851127.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0d43b024e3dc469ab7d99d6a2d71f474",
    "type":"Axure:Page",
    "name":"step2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"53571a329cd64e61b495f326d5cebda4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":0},
            "size":{
              "width":1000,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"936983f7b2414f019375ad1466993886",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":0},
                "size":{
                  "width":1000,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/step2_2/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "53571a329cd64e61b495f326d5cebda4":{
      "scriptId":"u0"},
    "936983f7b2414f019375ad1466993886":{
      "scriptId":"u1"}}});