$axure.loadCurrentPage({
  "url":"step3_3.html",
  "generationDate":new Date(1421638851291.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"717ceac9e9ca486ab6004e6cc69fa17d",
    "type":"Axure:Page",
    "name":"step3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1595ecb9c6f047f1b388aec7c371beb8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":1500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec0bae856351434f92c1beebf431232c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":1500}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"未登录：<br>显示求签文字，点击“告诉小伙伴”显示分享页面。已及按照用户选择的薪水范围、地区、行业、职能推出相对应的公司。"},
          "images":{
            "normal~":"images/step3_3/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "1595ecb9c6f047f1b388aec7c371beb8":{
      "scriptId":"u0"},
    "ec0bae856351434f92c1beebf431232c":{
      "scriptId":"u1"}}});