$axure.loadCurrentPage({
  "url":"天际网.html",
  "generationDate":new Date(1421638850934.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c7a53f3fc7494a3ba79c97627d38b413",
    "type":"Axure:Page",
    "name":"天际网",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f454ee56f8c43e08535ff28dc45c6c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":70},
            "size":{
              "width":30,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdf98aebb5de4fca840afe7ceca9c292",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":70},
                "size":{
                  "width":30,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微博/u0.png"}},
{
          "id":"c551f3f7390f49e0a2efec19a0e6bfd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":160,
              "y":60},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bbe0694e7b74a33980ceaac438a58dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":160,
                  "y":60},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b741c8871fa4b08b6e79d83c3230adb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 常规', '宋体'",
            "fontSize":"12px",
            "location":{
              "x":162,
              "y":78},
            "size":{
              "width":229,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c9c3c7462274317944fc0a44e750497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 常规', '宋体'",
                "fontSize":"12px",
                "location":{
                  "x":162,
                  "y":78},
                "size":{
                  "width":229,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc33aa1f3ab84a96857bebac5c9e347d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCC3300},
            "location":{
              "x":162,
              "y":102},
            "size":{
              "width":200,
              "height":158},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9f6af449504b72adaeb0e3499f5f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC3300},
                "location":{
                  "x":162,
                  "y":102},
                "size":{
                  "width":200,
                  "height":158},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/天际网/u6.png"}},
{
          "id":"9150e075bbca4c06acf20db1697df0be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":214,
              "y":124},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b81dc3645df406991b50e3ab7d060a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":214,
                  "y":124},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"484f01a763ec424ca8458c19f880d2f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":156},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0964622c796f4531af864c7c03372451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":217,
                  "y":156},
                "size":{
                  "width":90,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/天际网/u10.png"}},
{
          "id":"9d61aca801e14fc8a68844bc41c55af8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"23px",
            "location":{
              "x":238,
              "y":178},
            "size":{
              "width":47,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98fdcc6b0b3142558ccebe7ef94afde2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"23px",
                "location":{
                  "x":238,
                  "y":178},
                "size":{
                  "width":47,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4f454ee56f8c43e08535ff28dc45c6c2":{
      "scriptId":"u0"},
    "cdf98aebb5de4fca840afe7ceca9c292":{
      "scriptId":"u1"},
    "c551f3f7390f49e0a2efec19a0e6bfd3":{
      "scriptId":"u2"},
    "4bbe0694e7b74a33980ceaac438a58dd":{
      "scriptId":"u3"},
    "7b741c8871fa4b08b6e79d83c3230adb":{
      "scriptId":"u4"},
    "1c9c3c7462274317944fc0a44e750497":{
      "scriptId":"u5"},
    "fc33aa1f3ab84a96857bebac5c9e347d":{
      "scriptId":"u6"},
    "0a9f6af449504b72adaeb0e3499f5f8b":{
      "scriptId":"u7"},
    "9150e075bbca4c06acf20db1697df0be":{
      "scriptId":"u8"},
    "8b81dc3645df406991b50e3ab7d060a9":{
      "scriptId":"u9"},
    "484f01a763ec424ca8458c19f880d2f6":{
      "scriptId":"u10"},
    "0964622c796f4531af864c7c03372451":{
      "scriptId":"u11"},
    "9d61aca801e14fc8a68844bc41c55af8":{
      "scriptId":"u12"},
    "98fdcc6b0b3142558ccebe7ef94afde2":{
      "scriptId":"u13"}}});